// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zezswzxhoirxabzdnill.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplenN3enhob2lyeGFiemRuaWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODk3NDYsImV4cCI6MjA2NDg2NTc0Nn0.U4_JVqQ1MqEVXDV2rtoX0bP_oUSc0F5OSCniPKA8jUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);